import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { advanceSession, createSession, createUser, deleteUser, endSessionEarly, getActiveUser, getAttempts, getCurrentSession, getLearningState, getSession, getSessionQuestions, getUser, initializeUserData, invalidateSession, listUsers, removeWrongQuestion, renameUser, setActiveUser, submitAttempt } from "../src/lib/user-data.ts";

const attempt = (userId: string, questionExternalId: string, sessionId: string | null, learningContext: "normal" | "special" | "wrongReview", submissionId: string, isCorrect = false) => ({ userId, questionExternalId, sessionId, learningContext, submissionId, submittedAnswer: isCorrect ? "A" : "B", isCorrect, cumulativeAnswerDuration: 50 });

async function main() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "gongkao-m2-1-b-"));
  const data = path.join(root, "user-data.db");
  const bank = path.join(root, "question-bank.db");
  await fs.writeFile(bank, "unchanged public bank");
  await initializeUserData(data);
  const legacy = path.join(root, "legacy-user-data.db");
  const legacyDb = new DatabaseSync(legacy); legacyDb.exec("CREATE TABLE attempts(id INTEGER PRIMARY KEY, questionExternalId TEXT NOT NULL)"); legacyDb.close();
  await assert.rejects(initializeUserData(legacy), /旧开发结构/);
  const a = await createUser({ nickname: "A" }, data), b = await createUser({ nickname: "B" }, data);
  await setActiveUser(a.id, data); assert.equal((await getActiveUser(data))?.id, a.id);
  assert.equal((await renameUser(a.id, "Alice", data)).nickname, "Alice");
  const normal = await createSession({ userId: a.id, type: "normal", questionExternalIds: ["Q1", "Q2", "Q3"] }, data);
  await assert.rejects(createSession({ userId: a.id, type: "normal", questionExternalIds: ["Q4"] }, data));
  const special = await createSession({ userId: b.id, type: "special", questionExternalIds: ["B1"] }, data);
  assert.equal((await getCurrentSession(a.id, data))?.id, normal.id);
  await setActiveUser(b.id, data); assert.equal((await getCurrentSession(a.id, data))?.status, "in_progress");
  await assert.rejects(submitAttempt(attempt(a.id, "Q1", null, "normal", "no-session"), data));
  await assert.rejects(submitAttempt(attempt(b.id, "B1", normal.id, "normal", "cross-user"), data));
  await assert.rejects(submitAttempt(attempt(a.id, "Q2", normal.id, "normal", "future"), data));
  const first = await submitAttempt(attempt(a.id, "Q1", normal.id, "normal", "same-submit"), data);
  const replay = await submitAttempt(attempt(a.id, "Q1", normal.id, "normal", "same-submit"), data);
  assert.equal(first.id, replay.id); assert.equal((await getAttempts(data, a.id)).length, 1);
  assert.equal(first.cumulativeAnswerDuration, 50); assert.equal((await getLearningState(a.id, "Q1", data))?.isWrong, true);
  await advanceSession(normal.id, "Q1", data);
  await assert.rejects(submitAttempt(attempt(a.id, "Q1", normal.id, "normal", "old-question"), data));
  await advanceSession(normal.id, "Q2", data); await advanceSession(normal.id, "Q3", data);
  const complete = await getSession(normal.id, data); assert.equal(complete.status, "completed"); assert.equal(complete.traversedQuestionCount, 3); assert.equal(complete.answeredQuestionCount, 1);
  await assert.rejects(submitAttempt(attempt(a.id, "Q3", normal.id, "normal", "closed"), data));
  const later = await submitAttempt(attempt(a.id, "Q1", null, "wrongReview", "review-correct", true), data);
  assert.notEqual(later.id, first.id); assert.equal((await getLearningState(a.id, "Q1", data))?.isWrong, false);
  await assert.rejects(submitAttempt(attempt(a.id, "Q1", "fake", "wrongReview", "bad-review"), data));
  await submitAttempt(attempt(b.id, "B1", special.id, "special", "b-wrong"), data);
  await advanceSession(special.id, "B1", data); assert.equal((await getSession(special.id, data)).status, "completed");
  const early = await createSession({ userId: a.id, type: "special", questionExternalIds: ["E1", "E2"] }, data);
  await endSessionEarly(early.id, data); assert.equal((await getSession(early.id, data)).status, "ended");
  await assert.rejects(submitAttempt(attempt(a.id, "E1", early.id, "special", "ended"), data));
  const invalid = await createSession({ userId: a.id, type: "normal", questionExternalIds: ["W"] }, data);
  await submitAttempt(attempt(a.id, "W", invalid.id, "normal", "invalidate-wrong"), data);
  assert.equal((await getLearningState(a.id, "W", data))?.isWrong, true);
  await removeWrongQuestion(a.id, "W", data); await invalidateSession(invalid.id, data);
  assert.equal((await getAttempts(data, a.id)).some((x) => x.questionExternalId === "W"), true);
  assert.equal((await getLearningState(a.id, "W", data))?.isWrong, false);
  await assert.rejects(submitAttempt(attempt(a.id, "W", invalid.id, "normal", "invalidated"), data));
  await setActiveUser(b.id, data); await deleteUser(b.id, data);
  assert.equal(await getActiveUser(data), undefined); assert.equal(await getUser(b.id, data), undefined);
  assert.equal((await listUsers(data)).length, 1); assert.equal(await fs.readFile(bank, "utf8"), "unchanged public bank");
  await initializeUserData(data); assert.equal((await getSessionQuestions(normal.id, data)).length, 3); assert.equal((await getAttempts(data, a.id)).length, 3);
  console.log("M2.1-B tests: PASS");
}
void main();
