const app=document.querySelector("#app");let state,answered=false,startedAt=0,elapsed=0,busy=false,reviewMode=false,reviewId=null,touchY=0;
const esc=v=>String(v??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
const shell=body=>`<div class="app-shell">${body}</div>`;
const topbar=user=>`<header class="top"><button class="wordmark" id="home">gongkao</button>${user?`<button class="profile" id="account">${esc(user.nickname)}</button>`:""}</header>`;
const fail=()=>`<section class="notice"><b>暂时没能完成操作</b><span>请稍后重试。</span></section>`;
async function api(url,method="GET",data){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||"操作失败");return j}
const pause=()=>{if(startedAt){elapsed+=performance.now()-startedAt;startedAt=0}};const resume=()=>{if(!answered&&!startedAt&&!document.hidden)startedAt=performance.now()};
function bindHome(user){const h=app.querySelector("#home"),a=app.querySelector("#account");if(h)h.onclick=()=>void renderIdle(user);if(a)a.onclick=()=>void renderAccount(user)}
function resetQuestion(){answered=false;elapsed=0;resume()}
async function forward(){if(busy)return;busy=true;pause();try{if(reviewMode)return renderReview(await api("/api/study/wrong-review/forward","POST",{reviewId}));await api("/api/study/forward","POST",{});await load()}catch{app.insertAdjacentHTML("beforeend",fail())}finally{busy=false}}
function armPull(){const n=app.querySelector(".next-pull");if(!n)return;n.classList.add("armed");setTimeout(()=>n.classList.remove("armed"),450)}
addEventListener("wheel",e=>{if(e.deltaY>0&&innerHeight+scrollY>=document.documentElement.scrollHeight-5){armPull();if(e.deltaY>85)void forward()}},{passive:true});addEventListener("touchstart",e=>touchY=e.touches[0].clientY,{passive:true});addEventListener("touchend",e=>{if(touchY-e.changedTouches[0].clientY>95&&innerHeight+scrollY>=document.documentElement.scrollHeight-5){armPull();void forward()}},{passive:true});addEventListener("visibilitychange",()=>document.hidden?pause():resume());
function renderCreateUser(){app.innerHTML=shell(`${topbar()}<main class="welcome"><span>从一题开始</span><h1>把注意力，留给题目。</h1><p>创建一个本地学习档案，之后会自然回到上次学习的位置。</p><label>学习档案名称<input id="nickname" maxlength="30" placeholder="例如：小王" autofocus></label><button class="action primary" id="create">开始学习</button></main>`);app.querySelector("#create").onclick=async()=>{try{await api("/api/study/user","POST",{nickname:app.querySelector("#nickname").value});await load()}catch{app.insertAdjacentHTML("beforeend",fail())}}}
async function renderIdle(user){const modules=await api("/api/study/modules");app.innerHTML=shell(`${topbar(user)}<main class="landing"><section><span class="eyebrow">学习</span><h1>从当前这一题开始。</h1><p>不需要计划，开始就好。</p><button class="action primary" id="start">开始学习</button></section><nav class="quiet-nav"><button id="status">学习状态</button><button id="review">错题回顾</button><button id="special">专项训练</button><button id="manage">管理</button></nav><section class="module-strip"><span>专项</span>${modules.map(m=>`<button data-module="${esc(m)}">${esc(m)}</button>`).join("")}</section></main>`);bindHome(user);app.querySelector("#start").onclick=async()=>{await api("/api/study/start","POST",{});await load()};app.querySelector("#status").onclick=()=>void renderStatus(user);app.querySelector("#review").onclick=()=>void startReview(user);app.querySelector("#special").onclick=()=>void renderSpecialModules(false);app.querySelector("#manage").onclick=()=>void renderManage(user);app.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>renderSpecialChoice(b.dataset.module,false))}
function learningFrame(user,q,review=false){const mode=review?"错题回顾":"学习";return `${topbar(user)}<main class="study"><header class="study-chrome"><div class="study-context"><span>${mode}</span>${q.module?`<i>${esc(q.module)}</i>`:""}</div><div class="study-actions">${review?`<button class="text" id="leave">结束回顾</button>`:`<button class="text" id="refresh">换一组</button><button class="text" id="special">专项</button>`}</div></header><div class="study-stage"><article class="question-flow">${q.material?`<section class="material-context"><div class="material-kicker">阅读材料</div>${q.material.title?`<h2>${esc(q.material.title)}</h2>`:""}<div class="material-copy">${esc(q.material.content||"")}</div></section>`:""}<section class="question-prompt"><h1>${esc(q.stem)}</h1></section><div class="answer-list" aria-label="请选择答案">${q.options.map(o=>`<button class="answer" data-answer="${esc(o.key)}"><i>${esc(o.key)}</i><span>${esc(o.text)}</span></button>`).join("")}</div></article></div><footer class="next-pull"><span>继续向下拉，进入下一题</span><button class="text" id="continue">继续</button></footer></main>`}
function renderQuestion(current){reviewMode=false;reviewId=null;app.innerHTML=shell(learningFrame(current.user,current.question));bindHome(current.user);resetQuestion();app.querySelector("#refresh").onclick=async()=>{await api("/api/study/refresh","POST",{});await load()};app.querySelector("#special").onclick=()=>void renderSpecialModules(true);app.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>void submit(b.dataset.answer));app.querySelector("#continue").onclick=()=>void forward()}
async function submit(answer){if(answered||busy)return;answered=true;pause();try{const r=await api("/api/study/submit","POST",{selectedAnswer:answer,submissionId:crypto.randomUUID(),answerDuration:Math.round(elapsed/1000)});showFeedback(r,answer)}catch{app.insertAdjacentHTML("beforeend",fail())}}
function showFeedback(r,answer){app.querySelectorAll("[data-answer]").forEach(b=>{b.disabled=true;if(b.dataset.answer===answer)b.classList.add(r.isCorrect?"correct":"wrong");if(r.correctAnswer.includes(b.dataset.answer))b.classList.add("correct")});app.querySelector(".reading").insertAdjacentHTML("beforeend",`<section class="answer-reveal ${r.isCorrect?"good":"bad"}"><b>${r.isCorrect?"回答正确":"再想一想"}</b><p>你的答案 ${esc(answer)} · 正确答案 ${esc(r.correctAnswer.join("、"))}</p>${r.explanation?`<div><span>解析</span>${esc(r.explanation)}</div>`:""}</section>`)}
async function startReview(user){reviewMode=true;renderReview(await api("/api/study/wrong-review/start","POST",{}),user)}function renderReview(r,user=state.user){reviewId=r.reviewId;if(r.state==="review_completed"){app.innerHTML=shell(`${topbar(user)}<main class="completion"><span>错题回顾</span><h1>这一轮，先到这里。</h1><p>已回顾的题目不会在本轮再次出现。</p><button class="action primary" id="back">返回学习</button></main>`);app.querySelector("#back").onclick=()=>renderIdle(user);return}app.innerHTML=shell(learningFrame(user,r.question,true));bindHome(user);resetQuestion();app.querySelector("#leave").onclick=async()=>{await api("/api/study/wrong-review/leave","POST",{reviewId});reviewMode=false;renderIdle(user)};app.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>void submitReview(r.question.externalId,b.dataset.answer));app.querySelector("#continue").onclick=()=>void forward()}
async function submitReview(id,answer){if(answered)return;answered=true;pause();try{showFeedback(await api("/api/study/wrong-review/submit","POST",{reviewId,questionExternalId:id,selectedAnswer:answer,submissionId:crypto.randomUUID(),answerDuration:Math.round(elapsed/1000)}),answer)}catch{app.insertAdjacentHTML("beforeend",fail())}}
function trend(t){const max=Math.max(1,...t.points.map(p=>p.answeredCount));return `<section class="trend-flow"><header><b>学习趋势</b><span>${t.granularity==="day"?"每日":t.granularity==="week"?"每周":"每月"}</span></header><div>${t.points.map(p=>`<i title="${esc(p.label)}：${p.answeredCount}题" style="height:${Math.max(4,p.answeredCount/max*100)}%"></i>`).join("")}</div></section>`}
async function renderStatus(user,range="7d"){const s=await api(`/api/study/status?range=${range}`);app.innerHTML=shell(`${topbar(user)}<main class="status-page"><header><div><span class="eyebrow">学习状态</span><h1>我的学习近况</h1><p>不急，先看看你已经走了多远。</p></div><nav><button class="${s.range==="7d"?"on":""}" id="d7">7D</button><button class="${s.range==="all"?"on":""}" id="all">ALL</button></nav></header><section class="companion"><div class="lulu-figure"><i>噜</i><span></span><span></span></div><div class="facts-flow"><p><span>正确率</span><b>${s.accuracy==null?"—":`${Math.round(s.accuracy*100)}%`}</b></p><p><span>作答</span><b>${s.answeredCount}<small>题</small></b></p><p><span>平均用时</span><b>${s.averageAnswerDuration==null?"—":`${Math.round(s.averageAnswerDuration)} 秒`}</b></p></div></section>${trend(s.trend)}<section class="actions-flow"><button id="continue-learning"><b>${s.currentTraining.state==="ongoing"?"继续学习":"开始学习"}</b><span>${s.currentTraining.state==="ongoing"?"回到上次停下的位置":"从下一题开始"}</span></button><button id="review"><b>回顾错题 <em>${s.wrongCountCurrent}</em></b><span>错题不受时间范围影响</span></button></section><footer><button id="wrong-book">错题本</button><button id="manage">管理</button><button id="back">返回学习</button></footer></main>`);bindHome(user);app.querySelector("#d7").onclick=()=>renderStatus(user,"7d");app.querySelector("#all").onclick=()=>renderStatus(user,"all");app.querySelector("#continue-learning").onclick=async()=>{if(s.currentTraining.state==="ready")await api("/api/study/start","POST",{});await load()};app.querySelector("#review").onclick=()=>startReview(user);app.querySelector("#wrong-book").onclick=()=>renderWrongBook(user);app.querySelector("#manage").onclick=()=>renderManage(user);app.querySelector("#back").onclick=()=>renderIdle(user)}
async function renderManage(user){app.innerHTML=shell(`${topbar(user)}<main class="tools"><span class="eyebrow">管理</span><h1>学习资料与设置</h1><p>低频功能，安静地放在这里。</p><button id="history">训练历史</button><button id="special">专项训练</button><button id="account-tool">学习档案</button><button id="bank">题库管理</button><button class="text" id="back">返回学习状态</button></main>`);bindHome(user);app.querySelector("#history").onclick=()=>renderHistory(user);app.querySelector("#special").onclick=()=>renderSpecialModules(false);app.querySelector("#account-tool").onclick=()=>renderAccount(user);app.querySelector("#bank").onclick=()=>renderBank(user);app.querySelector("#back").onclick=()=>renderStatus(user)}
async function renderSpecialModules(replacing){const ms=await api("/api/study/modules");app.innerHTML=shell(`${topbar(state.user)}<main class="tools"><span class="eyebrow">专项训练</span><h1>选择一个模块</h1>${ms.map(m=>`<button data-module="${esc(m)}">${esc(m)}</button>`).join("")}<button class="text" id="back">返回</button></main>`);app.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>renderSpecialChoice(b.dataset.module,replacing));app.querySelector("#back").onclick=()=>load()}
function renderSpecialChoice(m,replacing){app.innerHTML=shell(`${topbar(state.user)}<main class="completion"><span>专项训练</span><h1>${esc(m)}</h1><p>${replacing?"将结束当前训练，改为这一组专项练习。":"从这个模块开始一组练习。"}</p><button class="action primary" id="go">开始专项训练</button><button class="text" id="back">返回</button></main>`);app.querySelector("#go").onclick=async()=>{await api("/api/study/special","POST",{module:m,replaceCurrent:replacing});await load()};app.querySelector("#back").onclick=()=>load()}
async function renderHistory(user){const d=await api("/api/study/history");app.innerHTML=shell(`${topbar(user)}<main class="tools history"><span class="eyebrow">训练历史</span><h1>每次训练</h1>${d.sessions.length?d.sessions.map(x=>`<div><b>${x.type==="special"?"专项训练":"普通训练"}</b><span>${x.status==="completed"?"已完成":x.status==="ended"?"提前结束":x.status==="invalidated"?"已撤销":"进行中"} · 已作答 ${x.completion.answeredCount}</span>${x.status!=="invalidated"?`<button data-id="${x.id}">撤销</button>`:""}</div>`).join(""):`<p>还没有训练记录。</p>`}<button class="text" id="back">返回管理</button></main>`);app.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{await api("/api/study/history/invalidate","POST",{sessionId:b.dataset.id});renderHistory(user)});app.querySelector("#back").onclick=()=>renderManage(user)}
async function renderWrongBook(user){const d=await api("/api/study/wrong-questions");app.innerHTML=shell(`${topbar(user)}<main class="tools"><span class="eyebrow">错题本</span><h1>当前错题</h1>${d.questionExternalIds.length?d.questionExternalIds.map(id=>`<div class="row">${esc(id)}<button data-id="${esc(id)}">移出</button></div>`).join(""):`<p>现在没有错题。</p>`}<button class="text" id="back">返回学习状态</button></main>`);app.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{await api("/api/study/wrong-questions/remove","POST",{questionExternalId:b.dataset.id});renderWrongBook(user)});app.querySelector("#back").onclick=()=>renderStatus(user)}
async function renderAccount(user){const d=await api("/api/study/users");app.innerHTML=shell(`${topbar(user)}<main class="tools"><span class="eyebrow">学习档案</span><h1>切换学习档案</h1>${d.users.map(x=>`<button data-user="${x.id}">${esc(x.nickname)}${x.id===user.id?"（当前）":""}</button>`).join("")}<button class="text" id="back">返回学习</button></main>`);app.querySelectorAll("[data-user]").forEach(b=>b.onclick=async()=>{await api("/api/study/user/active","POST",{userId:b.dataset.user});load()});app.querySelector("#back").onclick=()=>load()}
async function renderBank(user){const b=await api("/api/study/bank-summary");app.innerHTML=shell(`${topbar(user)}<main class="tools"><span class="eyebrow">题库管理</span><h1>本地题库</h1><p>${b.questions} 道题 · ${b.modules.length} 个模块</p>${b.modules.map(m=>`<div class="row">${esc(m.module)} <span>${m.count}</span></div>`).join("")}<button class="text" id="back">返回管理</button></main>`);app.querySelector("#back").onclick=()=>renderManage(user)}
function renderCompleted(c){const s=c.completion;app.innerHTML=shell(`${topbar(c.user)}<main class="completion"><span>本次训练</span><h1>这一组，完成了。</h1><p>已作答 ${s.answeredCount} 题，正确 ${s.correctCount} 题。${s.accuracy==null?"":` 正确率 ${Math.round(s.accuracy*100)}%。`}</p><button class="action primary" id="again">继续学习</button><button class="text" id="end">结束</button></main>`);app.querySelector("#again").onclick=async()=>{await api("/api/study/start","POST",{});load()};app.querySelector("#end").onclick=()=>renderIdle(c.user)}
async function load(){pause();if(!app.children.length)app.innerHTML=shell(`<main class="loading">正在准备学习内容…</main>`);state=await api("/api/study/current");if(state.state==="no_user")return renderCreateUser();if(state.state==="idle")return renderIdle(state.user);if(state.state==="completed")return renderCompleted(state);renderQuestion(state)}void load().catch(()=>app.innerHTML=shell(fail()));
