const app=document.querySelector("#app");let state,answered=false,started=0,elapsed=0,armed=false,busy=false,touchY=0;
const esc=v=>String(v??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
async function api(url,method="GET",data){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:data?JSON.stringify(data):undefined}),j=await r.json();if(!r.ok)throw Error(j.error);return j}
function pause(){if(started){elapsed+=performance.now()-started;started=0}} function resume(){if(!answered&&!started)started=performance.now()}
function bottom(){return innerHeight+scrollY>=document.documentElement.scrollHeight-4}
async function forward(){if(busy)return;busy=true;pause();try{await api("/api/study/forward","POST",{});await load()}finally{busy=false}}
function down(){if(!bottom()){armed=false;return}if(armed)forward();else armed=true}
addEventListener("wheel",e=>{if(e.deltaY>0)down();else armed=false},{passive:true});addEventListener("touchstart",e=>touchY=e.touches[0].clientY,{passive:true});addEventListener("touchend",e=>{if(touchY-e.changedTouches[0].clientY>45)down()},{passive:true});addEventListener("visibilitychange",()=>document.hidden?pause():resume());
async function load(){state=await api("/api/study/current");if(state.state==="no_user"){app.innerHTML='<h1>gongkao</h1><input id="name"><button id="create">开始学习</button>';app.querySelector("#create").onclick=async()=>{await api("/api/study/user","POST",{nickname:app.querySelector("#name").value});load()};return}if(state.state==="idle"){const modules=await api("/api/study/modules");app.innerHTML='<h1>gongkao</h1><button id="start">开始学习</button><section>专项训练：'+modules.map(m=>'<button data-module="'+esc(m)+'">'+esc(m)+'</button>').join("")+'</section>';app.querySelector("#start").onclick=async()=>{await api("/api/study/start","POST",{});load()};app.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>special(b.dataset.module));return}if(state.state==="completed"){const x=state.completion;app.innerHTML='<h1>本次学习完成</h1><p>已作答 '+x.answeredCount+'/'+x.plannedCount+'　正确 '+x.correctCount+'　错误 '+x.wrongCount+'　正确率 '+(x.accuracy==null?"—":Math.round(x.accuracy*100)+"%")+'　作答用时 '+x.answerDuration+' 秒</p><button id="again">继续学习</button>';app.querySelector("#again").onclick=async()=>{await api("/api/study/start","POST",{});load()};return}renderQuestion(state.question)}
function renderQuestion(q){answered=false;elapsed=0;started=performance.now();armed=false;app.innerHTML='<button id="refresh">换一组</button><div class="module">'+esc(q.module||"")+'</div>'+(q.material?'<div class="material">'+esc(q.material.content||q.material.title||"")+'</div>':"")+'<h2>'+esc(q.stem)+'</h2>'+q.options.map(o=>'<button class="option" data-answer="'+esc(o.key)+'">'+esc(o.key)+'. '+esc(o.text)+'</button>').join("")+'<div class="continue">继续向下滚动，进入下一题<br><button id="continue">继续向下</button></div>';app.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>submit(b.dataset.answer));app.querySelector("#refresh").onclick=async()=>{await api("/api/study/refresh","POST",{});load()};app.querySelector("#continue").onclick=forward}
async function special(module){const replace=state.state==="ongoing";if(replace&&!confirm("将结束当前训练并开始专项训练。继续吗？"))return;await api("/api/study/special","POST",{module,replaceCurrent:replace});load()}
async function submit(answer){if(answered)return;pause();answered=true;const r=await api("/api/study/submit","POST",{selectedAnswer:answer,submissionId:crypto.randomUUID(),answerDuration:Math.round(elapsed/1000)});app.querySelectorAll("[data-answer]").forEach(b=>{b.disabled=true;if(b.dataset.answer===answer)b.classList.add(r.isCorrect?"correct":"wrong");if(b.dataset.answer===r.correctAnswer[0])b.classList.add("correct")});app.insertAdjacentHTML("beforeend",'<div class="feedback"><b>'+(r.isCorrect?"正确":"回答错误")+'</b><br>你的答案：'+esc(answer)+'<br>正确答案：'+esc(r.correctAnswer.join("、"))+'</div>')}
load().catch(e=>app.textContent=e.message);
