import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import { initializeApplicationData, questionBankFile, userDataFile } from "./lib/app-data.js";
import { createUser, getActiveUser, replaceOngoingSession, setActiveUser } from "./lib/user-data.js";
import { createPlannedSession, generateSessionPlan } from "./lib/session-planner.js";
import { forwardCurrent, getCompletionStats, refreshSession, resumeSession, submitCurrentAnswer } from "./lib/session-runner.js";
import { getStudyBankSummary } from "./lib/study-question-bank.js";

const webRoot=path.join(process.cwd(),"src","web");
const reply=(res:http.ServerResponse,status:number,value:unknown,type="application/json; charset=utf-8")=>{res.writeHead(status,{"content-type":type});res.end(typeof value==="string"?value:JSON.stringify(value));};
const body=async(req:http.IncomingMessage)=>{let text="";for await(const chunk of req)text+=chunk;try{return JSON.parse(text||"{}") as Record<string,unknown>;}catch{throw new Error("请求格式无效");}};
async function current(){const user=await getActiveUser(userDataFile);if(!user)return {state:"no_user"};const p=await resumeSession({userId:user.id,userDataFile,questionBankFile});if(!p)return {state:"idle",user};if(!p.question)return {state:"completed",user,completion:await getCompletionStats(p.session.id,userDataFile)};const q=p.question;return {state:"ongoing",user,sessionType:p.session.type,question:{externalId:q.externalId,module:q.module,stem:q.stem,options:q.options.map(o=>({key:o.key,text:o.text})),material:q.material&&{title:q.material.title,content:q.material.content}}};}
async function main(){await initializeApplicationData();http.createServer(async(req,res)=>{try{const url=new URL(req.url??"/","http://localhost");if(url.pathname==="/"||url.pathname==="/app.js"||url.pathname==="/app.css"){const name=url.pathname==="/"?"index.html":url.pathname.slice(1);return reply(res,200,await fs.readFile(path.join(webRoot,name),"utf8"),name.endsWith(".css")?"text/css":"text/html; charset=utf-8");}if(url.pathname==="/api/study/current")return reply(res,200,await current());if(url.pathname==="/api/study/modules")return reply(res,200,(await getStudyBankSummary(questionBankFile)).modules.map(m=>m.module));const data=req.method==="POST"?await body(req):{};if(url.pathname==="/api/study/user"){const user=await createUser({nickname:String(data.nickname??"")},userDataFile);await setActiveUser(user.id,userDataFile);return reply(res,201,{user});}const user=await getActiveUser(userDataFile);if(!user)throw new Error("请先创建学习档案");const base={userId:user.id,userDataFile,questionBankFile};if(url.pathname==="/api/study/start"){await createPlannedSession({...base,type:"normal"});return reply(res,200,await current());}if(url.pathname==="/api/study/submit"){const r=await submitCurrentAnswer({...base,selectedAnswer:String(data.selectedAnswer??""),submissionId:String(data.submissionId??""),cumulativeAnswerDuration:Number(data.answerDuration??0)});return reply(res,200,{submittedAnswer:r.attempt.submittedAnswer,isCorrect:r.isCorrect,correctAnswer:r.correctAnswer,explanation:r.explanation});}if(url.pathname==="/api/study/forward"){await forwardCurrent(base);return reply(res,200,await current());}if(url.pathname==="/api/study/refresh"){await refreshSession(base);return reply(res,200,await current());}if(url.pathname==="/api/study/special"){const existing=await resumeSession(base);if(existing&&!data.replaceCurrent)return reply(res,409,{error:"当前有进行中的训练，请确认替换"});const plan=await generateSessionPlan({...base,type:"special",module:String(data.module??""),previousSessionId:existing?.session.id});if(existing)await replaceOngoingSession({userId:user.id,oldSessionId:existing.session.id,type:plan.type,questionExternalIds:plan.questionExternalIds},userDataFile);else await createPlannedSession({...base,type:"special",module:String(data.module??"")});return reply(res,200,await current());}return reply(res,404,{error:"Not found"});}catch(error){return reply(res,400,{error:error instanceof Error?error.message:"操作失败"});}}).listen(Number(process.env.PORT??3000));}void main();
